sf-dynamic-approvals/main/default/objects/ApprovalLock__c/ApprovalLock__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Approval Lock</label>
</CustomObject>

force-app/main/default/objects/ApprovalLock__c/fields/IsKeepLockedAfterProcess__c.field-meta.xml
<CustomField>
    <fullName>IsKeepLockedAfterProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keep Locked after Process?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApprovalLockTest.cls
@isTest
public class ApprovalLockTest {
    @isTest
    static void shouldReturnTrueBecauseRecordIdExistsInSetting() {
        Id opportunityId = ApprovalTestDataFactory.generateId(Opportunity.SObjectType);
        ApprovalLock__c lockOpportunity = new ApprovalLock__c(Name = opportunityId, IsKeepLockedAfterProcess__c = false);
        insert lockOpportunity;

        Test.startTest();
        System.assert(
            ApprovalLock.getInstance().isLocked(opportunityId),
            'ApprovalLock class did not successfully find the Custom Setting telling it that the Id is currently locked'
        );
        Test.stopTest();
    }

    @isTest
    static void shouldReturnFalseBecauseNothingThere() {
        Id opportunityId = ApprovalTestDataFactory.generateId(Opportunity.SObjectType);

        Test.startTest();
        System.assert(
            !ApprovalLock.getInstance().isLocked(opportunityId),
            'ApprovalLock class accidentally found that an Opp Id without Custom Setting for lock is locked'
        );
        Test.stopTest();
    }
}